### ISSUE TITLE
Loop bounding rewrites optimised LLVM IR incorrectly

### ISSUE THREAD

**Issue by albertnetymk** [nidhugg/nidhugg#86] opened 2020-05-11 19:47 UTC
Running it using `nidhuggc -O -std=c++17 -- --sc --unroll=5 test.cpp`, and the error msg is:
```
Instruction does not dominate all uses!
  %66 = load volatile i64, i64* @x, align 8, !dbg !249, !tbaa !166
  %69 = xor i64 %66, %13, !dbg !252
Instruction does not dominate all uses!
  %13 = select i1 %12, i64 0, i64 %11, !dbg !205
  %69 = xor i64 %66, %13, !dbg !252
LLVM ERROR: Broken module found, compilation aborted!
```
The error goes away if either `-O` or `unroll` is dropped. I tried both clang 9 and 10, and the error is the same.

## test.cpp
```cpp
#include <stdio.h>
#include <stdbool.h>

#include <cstdint>
#include <cassert>

struct Util {
  template<typename D, typename U, typename T>
    static D f(D volatile* dest,U compare_value,T exchange_value) {
      if (*dest == compare_value) {
        *dest = exchange_value;
        return compare_value;
      }
      return *dest;
    }
};

bool simulation_done = false;
using oop = uintptr_t;
struct Address {
  static bool is_bad(uintptr_t value) {
    return value;
  }
  static bool is_good(uintptr_t value) {
    return value;
  }
  static bool is_remapped(uintptr_t value) {
    return value & (0b100UL << 40);
  }
  static uintptr_t good(uintptr_t value) {
    return offset(value) | (0b001UL << 40);
  }
  static bool is_good_or_null(uintptr_t value) {
    return !is_bad(value);
  }
  static uintptr_t offset(uintptr_t value) {
    return value & ((1UL << 40) - 1);
  }
};
typedef bool (*BarrierFastPath)(uintptr_t);
typedef uintptr_t (*BarrierSlowPath)(uintptr_t);
struct Barrier {
  template <BarrierFastPath fast_path>
    static void self_heal(volatile oop* p, uintptr_t addr, uintptr_t heal_addr);
  template <BarrierFastPath fast_path, BarrierSlowPath slow_path>
    static oop barrier(volatile oop* p, oop o);
  static uintptr_t mark(uintptr_t addr);
  static uintptr_t load_barrier_on_oop_slow_path(uintptr_t addr);
  static oop load_barrier_on_oop_field(volatile oop* p);
};
template <BarrierFastPath fast_path>
inline void Barrier::self_heal(volatile oop* p, uintptr_t addr, uintptr_t heal_addr) {
  for (;;) {
    const uintptr_t prev_addr = Util::f((volatile uintptr_t*)p, addr, heal_addr);
    if (prev_addr == addr) {
      return;
    }
    assert(Address::offset(prev_addr) == Address::offset(heal_addr));
    addr = prev_addr;
  }
}
template <BarrierFastPath fast_path, BarrierSlowPath slow_path>
inline oop Barrier::barrier(volatile oop* p, oop o) {
  const uintptr_t addr = o;
  if (fast_path(addr)) {
    return addr;
  }
  const uintptr_t good_addr = slow_path(addr);
  if (p != NULL) {
    self_heal<fast_path>(p, addr, good_addr);
  }
  return good_addr;
}
inline oop Barrier::load_barrier_on_oop_field(volatile oop* p) {
  return barrier<Address::is_good_or_null, load_barrier_on_oop_slow_path>(p, *p);
}
uintptr_t Barrier::mark(uintptr_t addr) {
  uintptr_t good_addr = 0;
  if (Address::is_remapped(addr)) {
    good_addr = Address::good(addr);
  }
  return good_addr;
}
uintptr_t Barrier::load_barrier_on_oop_slow_path(uintptr_t addr) {
  return addr > 400 ? 0 : mark(addr);
}
uintptr_t x;
void f() {
  while (!simulation_done) {
    Barrier::load_barrier_on_oop_field(&x);
  }
}

int main() {
  return 0;
}
```

**Comment by kostis** [comment] 2020-05-20 18:04
Thanks for the report.  We will look into (and most likely fix) this, but I wanted to point out a more general issue.

In general, using compiler optimizations (`-O` and friends) is _not_ OK in Nidhugg or other stateless model checkers that use similar technology.  In programs that have errors, due to e.g. data races or other undefined behavior, the C compiler is allowed to do arbitrary rewrites / transformations to these programs when "optimizing" them.  So, in general, you are not encouraged to use options like `-O` when using `nidhuggc`.

Besides this word of caution, this also explains why we have not encountered issues like this one.  We do not normally use `-O`.

**Comment by albertnetymk** [comment] 2020-05-20 20:06
I see; thank you for the explanation.

**Comment by margnus1** [comment] 2022-11-01 11:27
Since c86fc867 we have a more robust loop bounder, and I can no longer reproduce this issue, so I'm closing it.

**Closed by margnus1** 2022-11-01 11:27 UTC
Labels: bug
